apiVersion: apps/v1
kind : Deployment
metadata:
  name: nginx-deployment
spec: 
  selector: 
    matchLabels:
       app: nginx-deployment
  template:
    metadata: 
      labels:
        app: nginx-deployment
    spec: 
      containers:
        - name:  service
          image: nginx:${version}
          ports: 
          - containerPort: 80
          env:
          - name: PORT 
            value: "80"
--- 
apiVersion: v1 
kind : Service 
metadata:
  name: nginx-deployment
spec: 
  type: ClusterIP
  selector: 
    app: nginx-deployment
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080
